name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages-source
jobs:
  publish:
    name: Publish to branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          branch: gh-pages-source
          directory: /dist
          update-branch: true